type AutoGenerated struct {
	ID     string `json:"id"`
	Map    string `json:"map"`
	Mode   string `json:"mode"`
	Ranked bool   `json:"ranked"`

	RoundResults []struct {
		RoundNum    int    `json:"roundNum"`
		PlantSite   string `json:"plantSite"`
		PlayerStats []struct {
			Kills  []interface{} `json:"kills"`
			Score  int           `json:"score"`
			Damage []struct {
				Damage    int    `json:"damage"`
				Legshots  int    `json:"legshots"`
				Receiver  string `json:"receiver"`
				Bodyshots int    `json:"bodyshots"`
				Headshots int    `json:"headshots"`
			} `json:"damage"`
			WasAfk  bool `json:"wasAfk"`
			Ability struct {
				GrenadeEffects  interface{} `json:"grenadeEffects"`
				Ability1Effects interface{} `json:"ability1Effects"`
				Ability2Effects interface{} `json:"ability2Effects"`
				UltimateEffects interface{} `json:"ultimateEffects"`
			} `json:"ability"`
			Economy struct {
				Armor        string `json:"armor"`
				Spent        int    `json:"spent"`
				Weapon       string `json:"weapon"`
				Remaining    int    `json:"remaining"`
				LoadoutValue int    `json:"loadoutValue"`
			} `json:"economy"`
			Subject      string `json:"subject"`
			WasPenalized bool   `json:"wasPenalized"`
		} `json:"playerStats"`
		RoundResult  string `json:"roundResult"`
		WinningTeam  string `json:"winningTeam"`
		PlayerScores []struct {
			Score   int    `json:"score"`
			Subject string `json:"subject"`
		} `json:"playerScores"`
		PlantLocation struct {
			X int `json:"x"`
			Y int `json:"y"`
		} `json:"plantLocation"`
		RoundCeremony  string `json:"roundCeremony"`
		DefuseLocation struct {
			X int `json:"x"`
			Y int `json:"y"`
		} `json:"defuseLocation"`
		PlantRoundTime  int `json:"plantRoundTime"`
		DefuseRoundTime int `json:"defuseRoundTime"`
		PlayerEconomies []struct {
			Armor        string `json:"armor"`
			Spent        int    `json:"spent"`
			Weapon       string `json:"weapon"`
			Subject      string `json:"subject"`
			Remaining    int    `json:"remaining"`
			LoadoutValue int    `json:"loadoutValue"`
		} `json:"playerEconomies"`
		RoundResultCode       string      `json:"roundResultCode"`
		PlantPlayerLocations  interface{} `json:"plantPlayerLocations"`
		DefusePlayerLocations interface{} `json:"defusePlayerLocations"`
		BombPlanter           string      `json:"bombPlanter,omitempty"`
		BombDefuser           string      `json:"bombDefuser,omitempty"`
	} `json:"roundResults"`
	Kills []struct {
		Round          int      `json:"round"`
		Killer         string   `json:"killer"`
		Victim         string   `json:"victim"`
		GameTime       int      `json:"gameTime"`
		RoundTime      int      `json:"roundTime"`
		Assistants     []string `json:"assistants"`
		VictimLocation struct {
			X int `json:"x"`
			Y int `json:"y"`
		} `json:"victimLocation"`
		FinishingDamage struct {
			DamageItem          string `json:"damageItem"`
			DamageType          string `json:"damageType"`
			IsSecondaryFireMode bool   `json:"isSecondaryFireMode"`
		} `json:"finishingDamage"`
		PlayerLocations []struct {
			Subject  string `json:"subject"`
			Location struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"location"`
			ViewRadians float64 `json:"viewRadians"`
		} `json:"playerLocations"`
	} `json:"kills"`
	Players []struct {
		Stats struct {
			Kills        int `json:"kills"`
			Score        int `json:"score"`
			Deaths       int `json:"deaths"`
			Assists      int `json:"assists"`
			AbilityCasts struct {
				GrenadeCasts  int `json:"grenadeCasts"`
				Ability1Casts int `json:"ability1Casts"`
				Ability2Casts int `json:"ability2Casts"`
				UltimateCasts int `json:"ultimateCasts"`
			} `json:"abilityCasts"`
			RoundsPlayed   int `json:"roundsPlayed"`
			PlaytimeMillis int `json:"playtimeMillis"`
		} `json:"stats"`
		TeamID      string `json:"teamId"`
		PartyID     string `json:"partyId"`
		Subject     string `json:"subject"`
		PlayerCard  string `json:"playerCard"`
		CharacterID string `json:"characterId"`
		PlayerTitle string `json:"playerTitle"`
		RoundDamage []struct {
			Round    int    `json:"round"`
			Damage   int    `json:"damage"`
			Receiver string `json:"receiver"`
		} `json:"roundDamage"`
		CompetitiveTier            int `json:"competitiveTier"`
		SessionPlaytimeMinutes     int `json:"sessionPlaytimeMinutes"`
		NewPlayerExperienceDetails struct {
			Ability struct {
				IdleTimeMillis              int `json:"idleTimeMillis"`
				ObjectiveCompleteTimeMillis int `json:"objectiveCompleteTimeMillis"`
			} `json:"ability"`
			BombPlant struct {
				IdleTimeMillis              int `json:"idleTimeMillis"`
				ObjectiveCompleteTimeMillis int `json:"objectiveCompleteTimeMillis"`
			} `json:"bombPlant"`
			AdaptiveBots struct {
				IdleTimeMillis                               int         `json:"idleTimeMillis"`
				KillDetailsFirstAttempt                      interface{} `json:"killDetailsFirstAttempt"`
				ObjectiveCompleteTimeMillis                  int         `json:"objectiveCompleteTimeMillis"`
				AdaptiveBotAverageDurationMillisAllAttempts  int         `json:"adaptiveBotAverageDurationMillisAllAttempts"`
				AdaptiveBotAverageDurationMillisFirstAttempt int         `json:"adaptiveBotAverageDurationMillisFirstAttempt"`
			} `json:"adaptiveBots"`
			BasicGunSkill struct {
				IdleTimeMillis              int `json:"idleTimeMillis"`
				ObjectiveCompleteTimeMillis int `json:"objectiveCompleteTimeMillis"`
			} `json:"basicGunSkill"`
			BasicMovement struct {
				IdleTimeMillis              int `json:"idleTimeMillis"`
				ObjectiveCompleteTimeMillis int `json:"objectiveCompleteTimeMillis"`
			} `json:"basicMovement"`
			SettingStatus struct {
				IsCrosshairDefault        bool `json:"isCrosshairDefault"`
				IsMouseSensitivityDefault bool `json:"isMouseSensitivityDefault"`
			} `json:"settingStatus"`
			DefendBombSite struct {
				Success                     bool `json:"success"`
				IdleTimeMillis              int  `json:"idleTimeMillis"`
				ObjectiveCompleteTimeMillis int  `json:"objectiveCompleteTimeMillis"`
			} `json:"defendBombSite"`
		} `json:"newPlayerExperienceDetails"`
	} `json:"players"`
	StartedAt time.Time `json:"startedAt"`
	Length    int       `json:"length"`
	Queue     string    `json:"queue"`
	Season    string    `json:"season"`
	Version   string    `json:"version"`
}