package config

const UNRANKED_LINK = "https://vignette.wikia.nocookie.net/valorant/images/b/b2/TX_CompetitiveTier_Large_0.png"
const IRON_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/7/7f/TX_CompetitiveTier_Large_3.png"
const IRON_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/2/28/TX_CompetitiveTier_Large_4.png"
const IRON_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/b/b8/TX_CompetitiveTier_Large_5.png"
const BRONZE_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/a/a2/TX_CompetitiveTier_Large_6.png"
const BRONZE_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/e/e7/TX_CompetitiveTier_Large_7.png"
const BRONZE_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/a/a8/TX_CompetitiveTier_Large_8.png"
const SILVER_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/0/09/TX_CompetitiveTier_Large_9.png"
const SILVER_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/c/ca/TX_CompetitiveTier_Large_10.png"
const SILVER_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/1/1e/TX_CompetitiveTier_Large_11.png"
const GOLD_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/9/91/TX_CompetitiveTier_Large_12.png"
const GOLD_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/4/45/TX_CompetitiveTier_Large_13.png"
const GOLD_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/c/c0/TX_CompetitiveTier_Large_14.png"
const PLATINUM_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/d/d3/TX_CompetitiveTier_Large_15.png"
const PLATINUM_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/a/a5/TX_CompetitiveTier_Large_16.png"
const PLATINUM_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/f/f2/TX_CompetitiveTier_Large_17.png"
const DIAMOND_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/b/b7/TX_CompetitiveTier_Large_18.png"
const DIAMOND_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/3/32/TX_CompetitiveTier_Large_19.png"
const DIAMOND_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/1/11/TX_CompetitiveTier_Large_20.png"
const IMMORTAL_1_LINK = "https://vignette.wikia.nocookie.net/valorant/images/8/86/TX_CompetitiveTier_Large_21.png"
const IMMORTAL_2_LINK = "https://vignette.wikia.nocookie.net/valorant/images/e/e5/TX_CompetitiveTier_Large_22.png"
const IMMORTAL_3_LINK = "https://vignette.wikia.nocookie.net/valorant/images/f/f9/TX_CompetitiveTier_Large_23.png"
const RADIANT_LINK = "https://vignette.wikia.nocookie.net/valorant/images/2/24/TX_CompetitiveTier_Large_24.png"